### ISSUE TITLE
fix: HTML `lang` attribute doesn't get updated when locale is changed (v.3.0.2)

### ISSUE THREAD

**Issue by ngocnn1104** [harlan-zw/nuxt-seo#429]
### 🐛 The bug

nuxt: 3.16.2
@nuxtjs/i18n: 9.5.3
@nuxtjs/seo: 3.0.2

After upgrading @nuxtjs/seo to 3.0.2, the `lang` attribute in the html element stops being reactive to i18n locale change.
I tried downgrading @nuxtjs/seo to 2.0.2, and it worked again.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-gnv3psvb?file=pages%2Findex.vue

### 🌈 Expected behavior

The `lang` attribute in the html element is reactive to i18n locale changes.

**Comment by harlan-zw** [comment]
I've pushed up a fix for this in Nuxt SEO Utils v7.0.9. You can opt in using the Nuxt SEO nightly until there's an official release: https://pkg.pr.new/harlan-zw/nuxt-seo/@nuxtjs/seo@586fb69

**Comment by victortrusov** [comment]
@harlan-zw would it be possible to release new version of Nuxt SEO with updated package? I see the latest release was > 1 month ago

**Comment by harlan-zw** [comment]
Oops, sorry for the delay... v3.1.0 out now

**Comment by eMeRiKa13** [comment]
Any news about this bug? I just updated to v3.1.0 but I still have the problem.
